version: '3.8'

services:
  dev_environment:
    build:
      context: .
      dockerfile: Dockerfile
    user: dev
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: hotel
      POSTGRES_HOSTNAME: postgres
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    network_mode: service:postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: hotel
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hotel.com
      PGADMIN_DEFAULT_PASSWORD: admin
    network_mode: service:postgres
    depends_on:
      - postgres

volumes:
  postgres-data:
