name: Gradle Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: ["17"]
        distribution: ["temurin"]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3.5.2
      - name: Set up JDK
        uses: actions/setup-java@v3.11.0
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: "gradle"
          check-latest: true
      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME
      - name: Execute Gradle Wrapper
        run: ./gradlew wrapper
      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Execute build
        run: ./gradlew build
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
